name: Very Super Duper Serious Team (VSDST)'s apporval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
    - name: label approved PR
      uses: abinoda/label-when-approved@1.0.7
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
